"""Fix exercise back_populate to backref

Revision ID: bbbf5b3a2dca
Revises: 5867f7b311b5
Create Date: 2026-02-06 11:00:56.450241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbf5b3a2dca'
down_revision: Union[str, Sequence[str], None] = '5867f7b311b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
